# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIs/EmployeeView.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_EmployeeView(object):
    def setupUi(self, EmployeeView):
        EmployeeView.setObjectName(_fromUtf8("EmployeeView"))
        EmployeeView.resize(1142, 711)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/favicon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        EmployeeView.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(EmployeeView)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 70, 1121, 631))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.lbl_name = QtGui.QFrame(self.tab)
        self.lbl_name.setGeometry(QtCore.QRect(10, 70, 1091, 221))
        self.lbl_name.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lbl_name.setFrameShadow(QtGui.QFrame.Raised)
        self.lbl_name.setObjectName(_fromUtf8("lbl_name"))
        self.lbl_bday = QtGui.QLabel(self.lbl_name)
        self.lbl_bday.setGeometry(QtCore.QRect(210, 70, 241, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_bday.setFont(font)
        self.lbl_bday.setObjectName(_fromUtf8("lbl_bday"))
        self.lbl_gender = QtGui.QLabel(self.lbl_name)
        self.lbl_gender.setGeometry(QtCore.QRect(210, 100, 141, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_gender.setFont(font)
        self.lbl_gender.setObjectName(_fromUtf8("lbl_gender"))
        self.lbl_profile_photo = QtGui.QLabel(self.lbl_name)
        self.lbl_profile_photo.setGeometry(QtCore.QRect(20, 10, 171, 171))
        self.lbl_profile_photo.setText(_fromUtf8(""))
        self.lbl_profile_photo.setPixmap(QtGui.QPixmap(_fromUtf8("icons/profilexxx.png")))
        self.lbl_profile_photo.setScaledContents(True)
        self.lbl_profile_photo.setObjectName(_fromUtf8("lbl_profile_photo"))
        self.lbl_address = QtGui.QLabel(self.lbl_name)
        self.lbl_address.setGeometry(QtCore.QRect(210, 130, 381, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_address.setFont(font)
        self.lbl_address.setObjectName(_fromUtf8("lbl_address"))
        self.lbl_gmail = QtGui.QLabel(self.lbl_name)
        self.lbl_gmail.setGeometry(QtCore.QRect(210, 160, 351, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_gmail.setFont(font)
        self.lbl_gmail.setObjectName(_fromUtf8("lbl_gmail"))
        self.lbl_username = QtGui.QLabel(self.lbl_name)
        self.lbl_username.setGeometry(QtCore.QRect(210, 40, 271, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_username.setFont(font)
        self.lbl_username.setObjectName(_fromUtf8("lbl_username"))
        self.lbl_contact = QtGui.QLabel(self.lbl_name)
        self.lbl_contact.setGeometry(QtCore.QRect(210, 190, 321, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_contact.setFont(font)
        self.lbl_contact.setObjectName(_fromUtf8("lbl_contact"))
        self.lbl_height = QtGui.QLabel(self.lbl_name)
        self.lbl_height.setGeometry(QtCore.QRect(640, 10, 151, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_height.setFont(font)
        self.lbl_height.setObjectName(_fromUtf8("lbl_height"))
        self.lbl_age = QtGui.QLabel(self.lbl_name)
        self.lbl_age.setGeometry(QtCore.QRect(640, 40, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_age.setFont(font)
        self.lbl_age.setObjectName(_fromUtf8("lbl_age"))
        self.lbl_status = QtGui.QLabel(self.lbl_name)
        self.lbl_status.setGeometry(QtCore.QRect(210, 10, 241, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_status.setFont(font)
        self.lbl_status.setObjectName(_fromUtf8("lbl_status"))
        self.lbl_start_date = QtGui.QLabel(self.lbl_name)
        self.lbl_start_date.setGeometry(QtCore.QRect(640, 70, 321, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_start_date.setFont(font)
        self.lbl_start_date.setObjectName(_fromUtf8("lbl_start_date"))
        self.lbl_presence_count = QtGui.QLabel(self.lbl_name)
        self.lbl_presence_count.setGeometry(QtCore.QRect(640, 100, 281, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_presence_count.setFont(font)
        self.lbl_presence_count.setObjectName(_fromUtf8("lbl_presence_count"))
        self.lbl_absence_count = QtGui.QLabel(self.lbl_name)
        self.lbl_absence_count.setGeometry(QtCore.QRect(640, 130, 281, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_absence_count.setFont(font)
        self.lbl_absence_count.setObjectName(_fromUtf8("lbl_absence_count"))
        self.generalInfo_frame = QtGui.QFrame(self.tab)
        self.generalInfo_frame.setGeometry(QtCore.QRect(10, 360, 901, 221))
        self.generalInfo_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.generalInfo_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.generalInfo_frame.setObjectName(_fromUtf8("generalInfo_frame"))
        self.lbl_position = QtGui.QLabel(self.generalInfo_frame)
        self.lbl_position.setGeometry(QtCore.QRect(20, 10, 301, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_position.setFont(font)
        self.lbl_position.setObjectName(_fromUtf8("lbl_position"))
        self.lbl_rate = QtGui.QLabel(self.generalInfo_frame)
        self.lbl_rate.setGeometry(QtCore.QRect(20, 40, 201, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_rate.setFont(font)
        self.lbl_rate.setObjectName(_fromUtf8("lbl_rate"))
        self.lbl_dayoff = QtGui.QLabel(self.generalInfo_frame)
        self.lbl_dayoff.setGeometry(QtCore.QRect(20, 70, 851, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_dayoff.setFont(font)
        self.lbl_dayoff.setObjectName(_fromUtf8("lbl_dayoff"))
        self.lbl_sss = QtGui.QLabel(self.generalInfo_frame)
        self.lbl_sss.setGeometry(QtCore.QRect(20, 100, 371, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_sss.setFont(font)
        self.lbl_sss.setObjectName(_fromUtf8("lbl_sss"))
        self.lbl_philhealth = QtGui.QLabel(self.generalInfo_frame)
        self.lbl_philhealth.setGeometry(QtCore.QRect(20, 130, 381, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_philhealth.setFont(font)
        self.lbl_philhealth.setObjectName(_fromUtf8("lbl_philhealth"))
        self.lbl_pagibig = QtGui.QLabel(self.generalInfo_frame)
        self.lbl_pagibig.setGeometry(QtCore.QRect(20, 160, 371, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_pagibig.setFont(font)
        self.lbl_pagibig.setObjectName(_fromUtf8("lbl_pagibig"))
        self.lbl_tin = QtGui.QLabel(self.generalInfo_frame)
        self.lbl_tin.setGeometry(QtCore.QRect(20, 190, 361, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_tin.setFont(font)
        self.lbl_tin.setObjectName(_fromUtf8("lbl_tin"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 20, 241, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(10, 310, 231, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.attendancelog_btn = QtGui.QToolButton(self.tab)
        self.attendancelog_btn.setGeometry(QtCore.QRect(930, 390, 171, 161))
        self.attendancelog_btn.setFocusPolicy(QtCore.Qt.TabFocus)
        self.attendancelog_btn.setStyleSheet(_fromUtf8("QToolButton{border: None;}"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/678120-calendar-clock-512.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.attendancelog_btn.setIcon(icon1)
        self.attendancelog_btn.setIconSize(QtCore.QSize(150, 150))
        self.attendancelog_btn.setObjectName(_fromUtf8("attendancelog_btn"))
        self.label_30 = QtGui.QLabel(self.tab)
        self.label_30.setGeometry(QtCore.QRect(950, 560, 141, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icons/profilexxx.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon2, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 181, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.frame = QtGui.QFrame(self.tab_2)
        self.frame.setGeometry(QtCore.QRect(20, 60, 741, 521))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(20, 20, 301, 231))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.lbl_days_present = QtGui.QLabel(self.frame_2)
        self.lbl_days_present.setGeometry(QtCore.QRect(20, 150, 271, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_days_present.setFont(font)
        self.lbl_days_present.setObjectName(_fromUtf8("lbl_days_present"))
        self.lbl_days_absent = QtGui.QLabel(self.frame_2)
        self.lbl_days_absent.setGeometry(QtCore.QRect(20, 190, 261, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_days_absent.setFont(font)
        self.lbl_days_absent.setObjectName(_fromUtf8("lbl_days_absent"))
        self.lbl_total_time = QtGui.QLabel(self.frame_2)
        self.lbl_total_time.setGeometry(QtCore.QRect(20, 70, 241, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_total_time.setFont(font)
        self.lbl_total_time.setObjectName(_fromUtf8("lbl_total_time"))
        self.label_5 = QtGui.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 181, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lbl_total_ot = QtGui.QLabel(self.frame_2)
        self.lbl_total_ot.setGeometry(QtCore.QRect(20, 110, 241, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_total_ot.setFont(font)
        self.lbl_total_ot.setObjectName(_fromUtf8("lbl_total_ot"))
        self.frame_3 = QtGui.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(20, 270, 421, 231))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.lbl_pagibig_2 = QtGui.QLabel(self.frame_3)
        self.lbl_pagibig_2.setGeometry(QtCore.QRect(20, 130, 381, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_pagibig_2.setFont(font)
        self.lbl_pagibig_2.setObjectName(_fromUtf8("lbl_pagibig_2"))
        self.lbl_philhealth_2 = QtGui.QLabel(self.frame_3)
        self.lbl_philhealth_2.setGeometry(QtCore.QRect(20, 100, 381, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_philhealth_2.setFont(font)
        self.lbl_philhealth_2.setObjectName(_fromUtf8("lbl_philhealth_2"))
        self.lbl_sss_2 = QtGui.QLabel(self.frame_3)
        self.lbl_sss_2.setGeometry(QtCore.QRect(20, 70, 381, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_sss_2.setFont(font)
        self.lbl_sss_2.setObjectName(_fromUtf8("lbl_sss_2"))
        self.label_6 = QtGui.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 181, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lbl_tax = QtGui.QLabel(self.frame_3)
        self.lbl_tax.setGeometry(QtCore.QRect(20, 160, 331, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_tax.setFont(font)
        self.lbl_tax.setObjectName(_fromUtf8("lbl_tax"))
        self.lbl_total_deductions = QtGui.QLabel(self.frame_3)
        self.lbl_total_deductions.setGeometry(QtCore.QRect(20, 190, 351, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_total_deductions.setFont(font)
        self.lbl_total_deductions.setObjectName(_fromUtf8("lbl_total_deductions"))
        self.lbl_special_pay = QtGui.QLabel(self.frame)
        self.lbl_special_pay.setGeometry(QtCore.QRect(370, 30, 361, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_special_pay.setFont(font)
        self.lbl_special_pay.setObjectName(_fromUtf8("lbl_special_pay"))
        self.lbl_gross_pay = QtGui.QLabel(self.frame)
        self.lbl_gross_pay.setGeometry(QtCore.QRect(370, 70, 361, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_gross_pay.setFont(font)
        self.lbl_gross_pay.setObjectName(_fromUtf8("lbl_gross_pay"))
        self.lbl_period = QtGui.QLabel(self.frame)
        self.lbl_period.setGeometry(QtCore.QRect(370, 110, 361, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_period.setFont(font)
        self.lbl_period.setObjectName(_fromUtf8("lbl_period"))
        self.lbl_status_2 = QtGui.QLabel(self.frame)
        self.lbl_status_2.setGeometry(QtCore.QRect(370, 150, 361, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_status_2.setFont(font)
        self.lbl_status_2.setObjectName(_fromUtf8("lbl_status_2"))
        self.netpay_frame = QtGui.QFrame(self.frame)
        self.netpay_frame.setGeometry(QtCore.QRect(450, 370, 271, 81))
        self.netpay_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.netpay_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.netpay_frame.setObjectName(_fromUtf8("netpay_frame"))
        self.lbl_net_pay = QtGui.QLabel(self.netpay_frame)
        self.lbl_net_pay.setGeometry(QtCore.QRect(10, 30, 251, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_net_pay.setFont(font)
        self.lbl_net_pay.setObjectName(_fromUtf8("lbl_net_pay"))
        self.scrollArea = QtGui.QScrollArea(self.tab_2)
        self.scrollArea.setGeometry(QtCore.QRect(780, 60, 311, 381))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 307, 377))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(780, 10, 181, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(950, 460, 141, 131))
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setPixmap(QtGui.QPixmap(_fromUtf8("icons/payroll.png")))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("icons/payroll.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon3, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.update_btn = QtGui.QPushButton(self.tab_3)
        self.update_btn.setGeometry(QtCore.QRect(940, 550, 151, 41))
        self.update_btn.setFocusPolicy(QtCore.Qt.TabFocus)
        self.update_btn.setStyleSheet(_fromUtf8("color: #fff;\n"
"background-color: rgb(21, 141, 141);\n"
"font: 14px/20px \"Helvetica Neue\",Helvetica,Arial,sans-serif;"))
        self.update_btn.setIconSize(QtCore.QSize(30, 30))
        self.update_btn.setObjectName(_fromUtf8("update_btn"))
        self.label_8 = QtGui.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(630, 300, 291, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans"))
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.generalInfo_frame_2 = QtGui.QFrame(self.tab_3)
        self.generalInfo_frame_2.setGeometry(QtCore.QRect(20, 310, 551, 281))
        self.generalInfo_frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.generalInfo_frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.generalInfo_frame_2.setObjectName(_fromUtf8("generalInfo_frame_2"))
        self.pagibig_txt = QtGui.QLineEdit(self.generalInfo_frame_2)
        self.pagibig_txt.setGeometry(QtCore.QRect(280, 150, 241, 33))
        self.pagibig_txt.setObjectName(_fromUtf8("pagibig_txt"))
        self.label_11 = QtGui.QLabel(self.generalInfo_frame_2)
        self.label_11.setGeometry(QtCore.QRect(10, 20, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.position_combo = QtGui.QComboBox(self.generalInfo_frame_2)
        self.position_combo.setGeometry(QtCore.QRect(100, 20, 151, 33))
        self.position_combo.setObjectName(_fromUtf8("position_combo"))
        self.label_13 = QtGui.QLabel(self.generalInfo_frame_2)
        self.label_13.setGeometry(QtCore.QRect(10, 100, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_12 = QtGui.QLabel(self.generalInfo_frame_2)
        self.label_12.setGeometry(QtCore.QRect(10, 60, 51, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.sss_txt = QtGui.QLineEdit(self.generalInfo_frame_2)
        self.sss_txt.setGeometry(QtCore.QRect(280, 30, 241, 33))
        self.sss_txt.setObjectName(_fromUtf8("sss_txt"))
        self.philhealth_txt = QtGui.QLineEdit(self.generalInfo_frame_2)
        self.philhealth_txt.setGeometry(QtCore.QRect(280, 90, 241, 33))
        self.philhealth_txt.setObjectName(_fromUtf8("philhealth_txt"))
        self.tin_txt = QtGui.QLineEdit(self.generalInfo_frame_2)
        self.tin_txt.setGeometry(QtCore.QRect(280, 210, 241, 33))
        self.tin_txt.setObjectName(_fromUtf8("tin_txt"))
        self.rate_combo = QtGui.QComboBox(self.generalInfo_frame_2)
        self.rate_combo.setGeometry(QtCore.QRect(100, 60, 151, 33))
        self.rate_combo.setObjectName(_fromUtf8("rate_combo"))
        self.label_26 = QtGui.QLabel(self.generalInfo_frame_2)
        self.label_26.setGeometry(QtCore.QRect(280, 10, 131, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.generalInfo_frame_2)
        self.label_27.setGeometry(QtCore.QRect(280, 70, 181, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.generalInfo_frame_2)
        self.label_28.setGeometry(QtCore.QRect(280, 130, 151, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(self.generalInfo_frame_2)
        self.label_29.setGeometry(QtCore.QRect(280, 190, 131, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.checkBox_tue = QtGui.QCheckBox(self.generalInfo_frame_2)
        self.checkBox_tue.setGeometry(QtCore.QRect(100, 130, 90, 23))
        self.checkBox_tue.setObjectName(_fromUtf8("checkBox_tue"))
        self.checkBox_wed = QtGui.QCheckBox(self.generalInfo_frame_2)
        self.checkBox_wed.setGeometry(QtCore.QRect(100, 160, 111, 23))
        self.checkBox_wed.setObjectName(_fromUtf8("checkBox_wed"))
        self.checkBox_sat = QtGui.QCheckBox(self.generalInfo_frame_2)
        self.checkBox_sat.setGeometry(QtCore.QRect(100, 250, 90, 23))
        self.checkBox_sat.setObjectName(_fromUtf8("checkBox_sat"))
        self.checkBox_fri = QtGui.QCheckBox(self.generalInfo_frame_2)
        self.checkBox_fri.setGeometry(QtCore.QRect(100, 220, 90, 23))
        self.checkBox_fri.setObjectName(_fromUtf8("checkBox_fri"))
        self.checkBox_mon = QtGui.QCheckBox(self.generalInfo_frame_2)
        self.checkBox_mon.setGeometry(QtCore.QRect(100, 100, 90, 23))
        self.checkBox_mon.setObjectName(_fromUtf8("checkBox_mon"))
        self.checkBox_thu = QtGui.QCheckBox(self.generalInfo_frame_2)
        self.checkBox_thu.setGeometry(QtCore.QRect(100, 190, 90, 23))
        self.checkBox_thu.setObjectName(_fromUtf8("checkBox_thu"))
        self.basicInfo_frame = QtGui.QFrame(self.tab_3)
        self.basicInfo_frame.setGeometry(QtCore.QRect(20, 40, 761, 231))
        self.basicInfo_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.basicInfo_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.basicInfo_frame.setObjectName(_fromUtf8("basicInfo_frame"))
        self.lname_txt = QtGui.QLineEdit(self.basicInfo_frame)
        self.lname_txt.setGeometry(QtCore.QRect(510, 40, 241, 33))
        self.lname_txt.setObjectName(_fromUtf8("lname_txt"))
        self.mname_txt = QtGui.QLineEdit(self.basicInfo_frame)
        self.mname_txt.setGeometry(QtCore.QRect(260, 40, 241, 33))
        self.mname_txt.setObjectName(_fromUtf8("mname_txt"))
        self.fname_txt = QtGui.QLineEdit(self.basicInfo_frame)
        self.fname_txt.setGeometry(QtCore.QRect(10, 40, 241, 33))
        self.fname_txt.setObjectName(_fromUtf8("fname_txt"))
        self.address_txt = QtGui.QLineEdit(self.basicInfo_frame)
        self.address_txt.setGeometry(QtCore.QRect(200, 110, 401, 33))
        self.address_txt.setObjectName(_fromUtf8("address_txt"))
        self.birthday_txt = QtGui.QDateEdit(self.basicInfo_frame)
        self.birthday_txt.setGeometry(QtCore.QRect(100, 170, 131, 33))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.birthday_txt.setFont(font)
        self.birthday_txt.setObjectName(_fromUtf8("birthday_txt"))
        self.label_15 = QtGui.QLabel(self.basicInfo_frame)
        self.label_15.setGeometry(QtCore.QRect(10, 170, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.male_radio = QtGui.QRadioButton(self.basicInfo_frame)
        self.male_radio.setGeometry(QtCore.QRect(330, 170, 107, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.male_radio.setFont(font)
        self.male_radio.setObjectName(_fromUtf8("male_radio"))
        self.female_radio = QtGui.QRadioButton(self.basicInfo_frame)
        self.female_radio.setGeometry(QtCore.QRect(330, 200, 107, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.female_radio.setFont(font)
        self.female_radio.setObjectName(_fromUtf8("female_radio"))
        self.label_16 = QtGui.QLabel(self.basicInfo_frame)
        self.label_16.setGeometry(QtCore.QRect(250, 170, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.height_txt = QtGui.QLineEdit(self.basicInfo_frame)
        self.height_txt.setGeometry(QtCore.QRect(610, 110, 141, 33))
        self.height_txt.setObjectName(_fromUtf8("height_txt"))
        self.contact_txt = QtGui.QLineEdit(self.basicInfo_frame)
        self.contact_txt.setGeometry(QtCore.QRect(10, 110, 181, 33))
        self.contact_txt.setObjectName(_fromUtf8("contact_txt"))
        self.frame_5 = QtGui.QFrame(self.basicInfo_frame)
        self.frame_5.setGeometry(QtCore.QRect(440, 170, 291, 41))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.inactive_radio = QtGui.QRadioButton(self.frame_5)
        self.inactive_radio.setGeometry(QtCore.QRect(170, 10, 101, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.inactive_radio.setFont(font)
        self.inactive_radio.setStyleSheet(_fromUtf8("color: rgb(255, 0, 4);"))
        self.inactive_radio.setObjectName(_fromUtf8("inactive_radio"))
        self.label_19 = QtGui.QLabel(self.frame_5)
        self.label_19.setGeometry(QtCore.QRect(10, 10, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.active_radio = QtGui.QRadioButton(self.frame_5)
        self.active_radio.setGeometry(QtCore.QRect(80, 10, 101, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.active_radio.setFont(font)
        self.active_radio.setStyleSheet(_fromUtf8("color: rgb(45, 132, 13);"))
        self.active_radio.setObjectName(_fromUtf8("active_radio"))
        self.label_20 = QtGui.QLabel(self.basicInfo_frame)
        self.label_20.setGeometry(QtCore.QRect(10, 10, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.basicInfo_frame)
        self.label_21.setGeometry(QtCore.QRect(260, 10, 131, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.basicInfo_frame)
        self.label_22.setGeometry(QtCore.QRect(510, 10, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.basicInfo_frame)
        self.label_23.setGeometry(QtCore.QRect(10, 80, 121, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.basicInfo_frame)
        self.label_24.setGeometry(QtCore.QRect(200, 80, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.basicInfo_frame)
        self.label_25.setGeometry(QtCore.QRect(610, 80, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_14 = QtGui.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(20, 0, 241, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_9 = QtGui.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(20, 270, 231, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_18 = QtGui.QLabel(self.tab_3)
        self.label_18.setGeometry(QtCore.QRect(980, 70, 121, 141))
        self.label_18.setText(_fromUtf8(""))
        self.label_18.setPixmap(QtGui.QPixmap(_fromUtf8("icons/settings2.png")))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.frame_4 = QtGui.QFrame(self.tab_3)
        self.frame_4.setGeometry(QtCore.QRect(630, 340, 461, 201))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.label_17 = QtGui.QLabel(self.frame_4)
        self.label_17.setGeometry(QtCore.QRect(20, 20, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_10 = QtGui.QLabel(self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(80, 20, 171, 91))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.train_btn = QtGui.QToolButton(self.frame_4)
        self.train_btn.setGeometry(QtCore.QRect(270, 20, 171, 161))
        self.train_btn.setStyleSheet(_fromUtf8("QToolButton{border: None;}"))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("icons/facerecoglogo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.train_btn.setIcon(icon4)
        self.train_btn.setIconSize(QtCore.QSize(200, 200))
        self.train_btn.setObjectName(_fromUtf8("train_btn"))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("icons/settings2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon5, _fromUtf8(""))
        self.lbl_id = QtGui.QLabel(self.centralwidget)
        self.lbl_id.setGeometry(QtCore.QRect(10, 40, 551, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_id.setFont(font)
        self.lbl_id.setObjectName(_fromUtf8("lbl_id"))
        self.lbl_name_2 = QtGui.QLabel(self.centralwidget)
        self.lbl_name_2.setGeometry(QtCore.QRect(10, 10, 681, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_name_2.setFont(font)
        self.lbl_name_2.setObjectName(_fromUtf8("lbl_name_2"))
        EmployeeView.setCentralWidget(self.centralwidget)

        self.retranslateUi(EmployeeView)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(EmployeeView)
        EmployeeView.setTabOrder(self.tabWidget, self.attendancelog_btn)
        EmployeeView.setTabOrder(self.attendancelog_btn, self.scrollArea)
        EmployeeView.setTabOrder(self.scrollArea, self.fname_txt)
        EmployeeView.setTabOrder(self.fname_txt, self.mname_txt)
        EmployeeView.setTabOrder(self.mname_txt, self.lname_txt)
        EmployeeView.setTabOrder(self.lname_txt, self.contact_txt)
        EmployeeView.setTabOrder(self.contact_txt, self.address_txt)
        EmployeeView.setTabOrder(self.address_txt, self.height_txt)
        EmployeeView.setTabOrder(self.height_txt, self.birthday_txt)
        EmployeeView.setTabOrder(self.birthday_txt, self.male_radio)
        EmployeeView.setTabOrder(self.male_radio, self.female_radio)
        EmployeeView.setTabOrder(self.female_radio, self.active_radio)
        EmployeeView.setTabOrder(self.active_radio, self.inactive_radio)
        EmployeeView.setTabOrder(self.inactive_radio, self.position_combo)
        EmployeeView.setTabOrder(self.position_combo, self.rate_combo)
        EmployeeView.setTabOrder(self.rate_combo, self.checkBox_mon)
        EmployeeView.setTabOrder(self.checkBox_mon, self.checkBox_tue)
        EmployeeView.setTabOrder(self.checkBox_tue, self.checkBox_wed)
        EmployeeView.setTabOrder(self.checkBox_wed, self.checkBox_thu)
        EmployeeView.setTabOrder(self.checkBox_thu, self.checkBox_fri)
        EmployeeView.setTabOrder(self.checkBox_fri, self.checkBox_sat)
        EmployeeView.setTabOrder(self.checkBox_sat, self.sss_txt)
        EmployeeView.setTabOrder(self.sss_txt, self.philhealth_txt)
        EmployeeView.setTabOrder(self.philhealth_txt, self.pagibig_txt)
        EmployeeView.setTabOrder(self.pagibig_txt, self.tin_txt)
        EmployeeView.setTabOrder(self.tin_txt, self.train_btn)
        EmployeeView.setTabOrder(self.train_btn, self.update_btn)

    def retranslateUi(self, EmployeeView):
        EmployeeView.setWindowTitle(_translate("EmployeeView", "Employee\'s Profile and Logs", None))
        self.lbl_bday.setText(_translate("EmployeeView", "Birthday: ", None))
        self.lbl_gender.setText(_translate("EmployeeView", "Gender: ", None))
        self.lbl_address.setText(_translate("EmployeeView", "Address: ", None))
        self.lbl_gmail.setText(_translate("EmployeeView", "Gmail: ", None))
        self.lbl_username.setText(_translate("EmployeeView", "Username: ", None))
        self.lbl_contact.setText(_translate("EmployeeView", "Contact No.: ", None))
        self.lbl_height.setText(_translate("EmployeeView", "Height: ", None))
        self.lbl_age.setText(_translate("EmployeeView", "Age: ", None))
        self.lbl_status.setText(_translate("EmployeeView", "Status: ", None))
        self.lbl_start_date.setText(_translate("EmployeeView", "Date Joined: ", None))
        self.lbl_presence_count.setText(_translate("EmployeeView", "No. of Days Present: ", None))
        self.lbl_absence_count.setText(_translate("EmployeeView", "No. of Days Absent:", None))
        self.lbl_position.setText(_translate("EmployeeView", "Position: ", None))
        self.lbl_rate.setText(_translate("EmployeeView", "Rate: ", None))
        self.lbl_dayoff.setText(_translate("EmployeeView", "Day-Off: ", None))
        self.lbl_sss.setText(_translate("EmployeeView", "SSS No.:  ", None))
        self.lbl_philhealth.setText(_translate("EmployeeView", "PHILHEALTH No.: ", None))
        self.lbl_pagibig.setText(_translate("EmployeeView", "PAG-IBIG No.: ", None))
        self.lbl_tin.setText(_translate("EmployeeView", "TIN: ", None))
        self.label.setText(_translate("EmployeeView", "Profile Information", None))
        self.label_2.setText(_translate("EmployeeView", "Job Information", None))
        self.attendancelog_btn.setText(_translate("EmployeeView", "...", None))
        self.label_30.setText(_translate("EmployeeView", "Attendance Logs", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("EmployeeView", "Profile", None))
        self.label_4.setText(_translate("EmployeeView", "Salary Report", None))
        self.lbl_days_present.setText(_translate("EmployeeView", "No. of Days Present: ", None))
        self.lbl_days_absent.setText(_translate("EmployeeView", "No. of Days Absent: ", None))
        self.lbl_total_time.setText(_translate("EmployeeView", "Total Time: ", None))
        self.label_5.setText(_translate("EmployeeView", "Time Report", None))
        self.lbl_total_ot.setText(_translate("EmployeeView", "Total Over Time: ", None))
        self.lbl_pagibig_2.setText(_translate("EmployeeView", "PAG-IBIG contribution: PHP ", None))
        self.lbl_philhealth_2.setText(_translate("EmployeeView", "PHILHEALTH Contribution: PHP ", None))
        self.lbl_sss_2.setText(_translate("EmployeeView", "SSS Contirbution: PHP ", None))
        self.label_6.setText(_translate("EmployeeView", "Deductions", None))
        self.lbl_tax.setText(_translate("EmployeeView", "Tax: PHP ", None))
        self.lbl_total_deductions.setText(_translate("EmployeeView", "Total: PHP ", None))
        self.lbl_special_pay.setText(_translate("EmployeeView", "Special Pay: PHP ", None))
        self.lbl_gross_pay.setText(_translate("EmployeeView", "Gross Pay: PHP ", None))
        self.lbl_period.setText(_translate("EmployeeView", "Period: ", None))
        self.lbl_status_2.setText(_translate("EmployeeView", "Status: ", None))
        self.lbl_net_pay.setText(_translate("EmployeeView", "Net Pay: PHP ", None))
        self.label_3.setText(_translate("EmployeeView", "Salary History", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("EmployeeView", "Salary Logs", None))
        self.update_btn.setText(_translate("EmployeeView", "Update Information", None))
        self.label_8.setText(_translate("EmployeeView", "Update Face Data Set", None))
        self.pagibig_txt.setPlaceholderText(_translate("EmployeeView", "PAGIBIG Number", None))
        self.label_11.setText(_translate("EmployeeView", "Position:", None))
        self.label_13.setText(_translate("EmployeeView", "Day-Off:", None))
        self.label_12.setText(_translate("EmployeeView", "Rate:", None))
        self.sss_txt.setPlaceholderText(_translate("EmployeeView", "SSS Number", None))
        self.philhealth_txt.setPlaceholderText(_translate("EmployeeView", "Philhealth Number", None))
        self.tin_txt.setPlaceholderText(_translate("EmployeeView", "TIN Number", None))
        self.label_26.setText(_translate("EmployeeView", "SSS Number:", None))
        self.label_27.setText(_translate("EmployeeView", "PHILHEALTH Number:", None))
        self.label_28.setText(_translate("EmployeeView", "PAGIBIG Number:", None))
        self.label_29.setText(_translate("EmployeeView", "TIN:", None))
        self.checkBox_tue.setText(_translate("EmployeeView", "Tuesday", None))
        self.checkBox_wed.setText(_translate("EmployeeView", "Wednesday", None))
        self.checkBox_sat.setText(_translate("EmployeeView", "Saturday", None))
        self.checkBox_fri.setText(_translate("EmployeeView", "Friday", None))
        self.checkBox_mon.setText(_translate("EmployeeView", "Monday", None))
        self.checkBox_thu.setText(_translate("EmployeeView", "Thursday", None))
        self.lname_txt.setPlaceholderText(_translate("EmployeeView", "Last Name", None))
        self.mname_txt.setPlaceholderText(_translate("EmployeeView", "Middle Name", None))
        self.fname_txt.setPlaceholderText(_translate("EmployeeView", "First Name", None))
        self.address_txt.setPlaceholderText(_translate("EmployeeView", "Address", None))
        self.birthday_txt.setDisplayFormat(_translate("EmployeeView", "yyyy-MM-dd", None))
        self.label_15.setText(_translate("EmployeeView", "Birthday:", None))
        self.male_radio.setText(_translate("EmployeeView", "Male", None))
        self.female_radio.setText(_translate("EmployeeView", "Female", None))
        self.label_16.setText(_translate("EmployeeView", "Gender:", None))
        self.height_txt.setPlaceholderText(_translate("EmployeeView", "Height", None))
        self.contact_txt.setPlaceholderText(_translate("EmployeeView", "Contact Number", None))
        self.inactive_radio.setText(_translate("EmployeeView", "Inactive", None))
        self.label_19.setText(_translate("EmployeeView", "Status:", None))
        self.active_radio.setText(_translate("EmployeeView", "Active", None))
        self.label_20.setText(_translate("EmployeeView", "First Name:", None))
        self.label_21.setText(_translate("EmployeeView", "Middle Name:", None))
        self.label_22.setText(_translate("EmployeeView", "Last Name:", None))
        self.label_23.setText(_translate("EmployeeView", "Contact No:", None))
        self.label_24.setText(_translate("EmployeeView", "Address:", None))
        self.label_25.setText(_translate("EmployeeView", "Height:", None))
        self.label_14.setText(_translate("EmployeeView", "Profile Information", None))
        self.label_9.setText(_translate("EmployeeView", "Job Configurations", None))
        self.label_17.setText(_translate("EmployeeView", "<html><head/><body><p><span style=\" color:orangered;\">NOTE: </span></p></body></html>", None))
        self.label_10.setText(_translate("EmployeeView", "Please only use this if the\n"
" user\'s face could not be\n"
" recognized anymore.\n"
" I am saving you time\n"
" dude.", None))
        self.train_btn.setText(_translate("EmployeeView", "...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("EmployeeView", "Settings and Configurations", None))
        self.lbl_id.setText(_translate("EmployeeView", "ID: ", None))
        self.lbl_name_2.setText(_translate("EmployeeView", "Name: ", None))

