# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIs/GlobalConfigWindow.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_UpdateConfigWindow(object):
    def setupUi(self, UpdateConfigWindow):
        UpdateConfigWindow.setObjectName(_fromUtf8("UpdateConfigWindow"))
        UpdateConfigWindow.resize(789, 475)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/favicon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        UpdateConfigWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(UpdateConfigWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.generalInfo_frame = QtGui.QFrame(self.centralwidget)
        self.generalInfo_frame.setGeometry(QtCore.QRect(10, 90, 771, 321))
        self.generalInfo_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.generalInfo_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.generalInfo_frame.setObjectName(_fromUtf8("generalInfo_frame"))
        self.start_combo = QtGui.QComboBox(self.generalInfo_frame)
        self.start_combo.setGeometry(QtCore.QRect(170, 20, 161, 33))
        self.start_combo.setObjectName(_fromUtf8("start_combo"))
        self.label_5 = QtGui.QLabel(self.generalInfo_frame)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 121, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.generalInfo_frame)
        self.label_6.setGeometry(QtCore.QRect(10, 70, 151, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.end_combo = QtGui.QComboBox(self.generalInfo_frame)
        self.end_combo.setGeometry(QtCore.QRect(170, 70, 161, 33))
        self.end_combo.setObjectName(_fromUtf8("end_combo"))
        self.label_7 = QtGui.QLabel(self.generalInfo_frame)
        self.label_7.setGeometry(QtCore.QRect(10, 120, 121, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.generalInfo_frame)
        self.label_8.setGeometry(QtCore.QRect(10, 170, 121, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.generalInfo_frame)
        self.label_9.setGeometry(QtCore.QRect(10, 220, 121, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.generalInfo_frame)
        self.label_10.setGeometry(QtCore.QRect(10, 270, 151, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lvl_1_rate_edit = QtGui.QDoubleSpinBox(self.generalInfo_frame)
        self.lvl_1_rate_edit.setGeometry(QtCore.QRect(170, 120, 161, 33))
        self.lvl_1_rate_edit.setMinimum(50.0)
        self.lvl_1_rate_edit.setMaximum(1000.0)
        self.lvl_1_rate_edit.setObjectName(_fromUtf8("lvl_1_rate_edit"))
        self.lvl_2_rate_edit = QtGui.QDoubleSpinBox(self.generalInfo_frame)
        self.lvl_2_rate_edit.setGeometry(QtCore.QRect(170, 170, 161, 33))
        self.lvl_2_rate_edit.setMinimum(50.0)
        self.lvl_2_rate_edit.setMaximum(1000.0)
        self.lvl_2_rate_edit.setObjectName(_fromUtf8("lvl_2_rate_edit"))
        self.lvl_3_rate_edit = QtGui.QDoubleSpinBox(self.generalInfo_frame)
        self.lvl_3_rate_edit.setGeometry(QtCore.QRect(170, 220, 161, 33))
        self.lvl_3_rate_edit.setMinimum(50.0)
        self.lvl_3_rate_edit.setMaximum(1000.0)
        self.lvl_3_rate_edit.setObjectName(_fromUtf8("lvl_3_rate_edit"))
        self.ot_rate_edit = QtGui.QDoubleSpinBox(self.generalInfo_frame)
        self.ot_rate_edit.setGeometry(QtCore.QRect(170, 270, 161, 33))
        self.ot_rate_edit.setObjectName(_fromUtf8("ot_rate_edit"))
        self.sss_pday = QtGui.QComboBox(self.generalInfo_frame)
        self.sss_pday.setGeometry(QtCore.QRect(600, 20, 161, 33))
        self.sss_pday.setObjectName(_fromUtf8("sss_pday"))
        self.label_11 = QtGui.QLabel(self.generalInfo_frame)
        self.label_11.setGeometry(QtCore.QRect(380, 20, 171, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.generalInfo_frame)
        self.label_12.setGeometry(QtCore.QRect(380, 70, 211, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.philhealth_pday = QtGui.QComboBox(self.generalInfo_frame)
        self.philhealth_pday.setGeometry(QtCore.QRect(600, 70, 161, 33))
        self.philhealth_pday.setObjectName(_fromUtf8("philhealth_pday"))
        self.label_13 = QtGui.QLabel(self.generalInfo_frame)
        self.label_13.setGeometry(QtCore.QRect(380, 120, 171, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.pagibig_pday = QtGui.QComboBox(self.generalInfo_frame)
        self.pagibig_pday.setGeometry(QtCore.QRect(600, 120, 161, 33))
        self.pagibig_pday.setObjectName(_fromUtf8("pagibig_pday"))
        self.label_14 = QtGui.QLabel(self.generalInfo_frame)
        self.label_14.setGeometry(QtCore.QRect(380, 170, 171, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.tax_pday = QtGui.QComboBox(self.generalInfo_frame)
        self.tax_pday.setGeometry(QtCore.QRect(600, 170, 161, 33))
        self.tax_pday.setObjectName(_fromUtf8("tax_pday"))
        self.cancel_btn = QtGui.QPushButton(self.centralwidget)
        self.cancel_btn.setGeometry(QtCore.QRect(670, 420, 111, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cancel_btn.setFont(font)
        self.cancel_btn.setFocusPolicy(QtCore.Qt.TabFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancel_btn.setIcon(icon1)
        self.cancel_btn.setIconSize(QtCore.QSize(30, 30))
        self.cancel_btn.setObjectName(_fromUtf8("cancel_btn"))
        self.update_btn = QtGui.QPushButton(self.centralwidget)
        self.update_btn.setGeometry(QtCore.QRect(550, 420, 111, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.update_btn.setFont(font)
        self.update_btn.setFocusPolicy(QtCore.Qt.TabFocus)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icons/recs.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.update_btn.setIcon(icon2)
        self.update_btn.setIconSize(QtCore.QSize(30, 30))
        self.update_btn.setObjectName(_fromUtf8("update_btn"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(370, 10, 71, 71))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("icons/settings2.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(450, 340, 321, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.enable_radio = QtGui.QRadioButton(self.centralwidget)
        self.enable_radio.setGeometry(QtCore.QRect(570, 311, 101, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.enable_radio.setFont(font)
        self.enable_radio.setStyleSheet(_fromUtf8("color: rgb(45, 132, 13);"))
        self.enable_radio.setObjectName(_fromUtf8("enable_radio"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(390, 340, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet(_fromUtf8("color: orangered;"))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.disable_radio = QtGui.QRadioButton(self.centralwidget)
        self.disable_radio.setGeometry(QtCore.QRect(670, 311, 111, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.disable_radio.setFont(font)
        self.disable_radio.setStyleSheet(_fromUtf8("color: rgb(255, 0, 4);"))
        self.disable_radio.setObjectName(_fromUtf8("disable_radio"))
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(390, 310, 181, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        UpdateConfigWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(UpdateConfigWindow)
        QtCore.QMetaObject.connectSlotsByName(UpdateConfigWindow)
        UpdateConfigWindow.setTabOrder(self.start_combo, self.end_combo)
        UpdateConfigWindow.setTabOrder(self.end_combo, self.lvl_1_rate_edit)
        UpdateConfigWindow.setTabOrder(self.lvl_1_rate_edit, self.lvl_2_rate_edit)
        UpdateConfigWindow.setTabOrder(self.lvl_2_rate_edit, self.lvl_3_rate_edit)
        UpdateConfigWindow.setTabOrder(self.lvl_3_rate_edit, self.ot_rate_edit)
        UpdateConfigWindow.setTabOrder(self.ot_rate_edit, self.sss_pday)
        UpdateConfigWindow.setTabOrder(self.sss_pday, self.philhealth_pday)
        UpdateConfigWindow.setTabOrder(self.philhealth_pday, self.pagibig_pday)
        UpdateConfigWindow.setTabOrder(self.pagibig_pday, self.tax_pday)
        UpdateConfigWindow.setTabOrder(self.tax_pday, self.enable_radio)
        UpdateConfigWindow.setTabOrder(self.enable_radio, self.disable_radio)
        UpdateConfigWindow.setTabOrder(self.disable_radio, self.update_btn)
        UpdateConfigWindow.setTabOrder(self.update_btn, self.cancel_btn)

    def retranslateUi(self, UpdateConfigWindow):
        UpdateConfigWindow.setWindowTitle(_translate("UpdateConfigWindow", "Global Configurations", None))
        self.label_5.setText(_translate("UpdateConfigWindow", "First Cut-Off:", None))
        self.label_6.setText(_translate("UpdateConfigWindow", "Second Cut-Off:", None))
        self.label_7.setText(_translate("UpdateConfigWindow", "Level 1 Rate:", None))
        self.label_8.setText(_translate("UpdateConfigWindow", "Level 2 Rate:", None))
        self.label_9.setText(_translate("UpdateConfigWindow", "Level 3 Rate:", None))
        self.label_10.setText(_translate("UpdateConfigWindow", "Over Time Rate:", None))
        self.lvl_1_rate_edit.setPrefix(_translate("UpdateConfigWindow", "PHP ", None))
        self.lvl_2_rate_edit.setPrefix(_translate("UpdateConfigWindow", "PHP ", None))
        self.lvl_3_rate_edit.setPrefix(_translate("UpdateConfigWindow", "PHP ", None))
        self.label_11.setText(_translate("UpdateConfigWindow", "SSS Payment:", None))
        self.label_12.setText(_translate("UpdateConfigWindow", "PHILHEALTH Payment:", None))
        self.label_13.setText(_translate("UpdateConfigWindow", "PAGIBIG Payment:", None))
        self.label_14.setText(_translate("UpdateConfigWindow", "Tax Payment:", None))
        self.cancel_btn.setText(_translate("UpdateConfigWindow", "Cancel", None))
        self.update_btn.setText(_translate("UpdateConfigWindow", "Update", None))
        self.label_15.setText(_translate("UpdateConfigWindow", "Disabling this will stop all processes and\n"
" will not permit all transactional operations", None))
        self.enable_radio.setText(_translate("UpdateConfigWindow", "Enabled", None))
        self.label_17.setText(_translate("UpdateConfigWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">NOTE: </span></p></body></html>", None))
        self.disable_radio.setText(_translate("UpdateConfigWindow", "Disabled", None))
        self.label_19.setText(_translate("UpdateConfigWindow", "Operational Status:", None))

