# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIs/RegisterWindow.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_RegisterWindow(object):
    def setupUi(self, RegisterWindow):
        RegisterWindow.setObjectName(_fromUtf8("RegisterWindow"))
        RegisterWindow.resize(782, 702)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/favicon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RegisterWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(RegisterWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.basicInfo_frame = QtGui.QFrame(self.centralwidget)
        self.basicInfo_frame.setGeometry(QtCore.QRect(10, 50, 761, 311))
        self.basicInfo_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.basicInfo_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.basicInfo_frame.setObjectName(_fromUtf8("basicInfo_frame"))
        self.username_txt = QtGui.QLineEdit(self.basicInfo_frame)
        self.username_txt.setGeometry(QtCore.QRect(10, 40, 241, 33))
        self.username_txt.setObjectName(_fromUtf8("username_txt"))
        self.password_txt = QtGui.QLineEdit(self.basicInfo_frame)
        self.password_txt.setGeometry(QtCore.QRect(260, 40, 241, 33))
        self.password_txt.setObjectName(_fromUtf8("password_txt"))
        self.gmail_txt = QtGui.QLineEdit(self.basicInfo_frame)
        self.gmail_txt.setGeometry(QtCore.QRect(10, 180, 241, 33))
        self.gmail_txt.setObjectName(_fromUtf8("gmail_txt"))
        self.confirm_txt = QtGui.QLineEdit(self.basicInfo_frame)
        self.confirm_txt.setGeometry(QtCore.QRect(510, 40, 241, 33))
        self.confirm_txt.setObjectName(_fromUtf8("confirm_txt"))
        self.lname_txt = QtGui.QLineEdit(self.basicInfo_frame)
        self.lname_txt.setGeometry(QtCore.QRect(510, 110, 241, 33))
        self.lname_txt.setObjectName(_fromUtf8("lname_txt"))
        self.mname_txt = QtGui.QLineEdit(self.basicInfo_frame)
        self.mname_txt.setGeometry(QtCore.QRect(260, 110, 241, 33))
        self.mname_txt.setObjectName(_fromUtf8("mname_txt"))
        self.fname_txt = QtGui.QLineEdit(self.basicInfo_frame)
        self.fname_txt.setGeometry(QtCore.QRect(10, 110, 241, 33))
        self.fname_txt.setObjectName(_fromUtf8("fname_txt"))
        self.address_txt = QtGui.QLineEdit(self.basicInfo_frame)
        self.address_txt.setGeometry(QtCore.QRect(260, 180, 491, 33))
        self.address_txt.setObjectName(_fromUtf8("address_txt"))
        self.birthday_txt = QtGui.QDateEdit(self.basicInfo_frame)
        self.birthday_txt.setGeometry(QtCore.QRect(100, 230, 131, 33))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.birthday_txt.setFont(font)
        self.birthday_txt.setObjectName(_fromUtf8("birthday_txt"))
        self.label_3 = QtGui.QLabel(self.basicInfo_frame)
        self.label_3.setGeometry(QtCore.QRect(10, 230, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.male_radio = QtGui.QRadioButton(self.basicInfo_frame)
        self.male_radio.setGeometry(QtCore.QRect(330, 230, 71, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.male_radio.setFont(font)
        self.male_radio.setObjectName(_fromUtf8("male_radio"))
        self.female_radio = QtGui.QRadioButton(self.basicInfo_frame)
        self.female_radio.setGeometry(QtCore.QRect(330, 260, 81, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.female_radio.setFont(font)
        self.female_radio.setObjectName(_fromUtf8("female_radio"))
        self.label_4 = QtGui.QLabel(self.basicInfo_frame)
        self.label_4.setGeometry(QtCore.QRect(250, 230, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.height_txt = QtGui.QLineEdit(self.basicInfo_frame)
        self.height_txt.setGeometry(QtCore.QRect(410, 260, 141, 33))
        self.height_txt.setObjectName(_fromUtf8("height_txt"))
        self.contact_txt = QtGui.QLineEdit(self.basicInfo_frame)
        self.contact_txt.setGeometry(QtCore.QRect(560, 260, 191, 33))
        self.contact_txt.setObjectName(_fromUtf8("contact_txt"))
        self.label_10 = QtGui.QLabel(self.basicInfo_frame)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 121, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.basicInfo_frame)
        self.label_11.setGeometry(QtCore.QRect(260, 10, 101, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.basicInfo_frame)
        self.label_12.setGeometry(QtCore.QRect(510, 10, 181, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.basicInfo_frame)
        self.label_13.setGeometry(QtCore.QRect(10, 80, 101, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.basicInfo_frame)
        self.label_14.setGeometry(QtCore.QRect(260, 80, 131, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.basicInfo_frame)
        self.label_15.setGeometry(QtCore.QRect(510, 80, 121, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.basicInfo_frame)
        self.label_16.setGeometry(QtCore.QRect(10, 150, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.basicInfo_frame)
        self.label_17.setGeometry(QtCore.QRect(260, 150, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.basicInfo_frame)
        self.label_18.setGeometry(QtCore.QRect(410, 230, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.basicInfo_frame)
        self.label_19.setGeometry(QtCore.QRect(560, 230, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.generalInfo_frame = QtGui.QFrame(self.centralwidget)
        self.generalInfo_frame.setGeometry(QtCore.QRect(10, 410, 521, 281))
        self.generalInfo_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.generalInfo_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.generalInfo_frame.setObjectName(_fromUtf8("generalInfo_frame"))
        self.position_combo = QtGui.QComboBox(self.generalInfo_frame)
        self.position_combo.setGeometry(QtCore.QRect(100, 20, 151, 33))
        self.position_combo.setObjectName(_fromUtf8("position_combo"))
        self.label_5 = QtGui.QLabel(self.generalInfo_frame)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.generalInfo_frame)
        self.label_6.setGeometry(QtCore.QRect(10, 60, 51, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.rate_combo = QtGui.QComboBox(self.generalInfo_frame)
        self.rate_combo.setGeometry(QtCore.QRect(100, 60, 151, 33))
        self.rate_combo.setObjectName(_fromUtf8("rate_combo"))
        self.label_7 = QtGui.QLabel(self.generalInfo_frame)
        self.label_7.setGeometry(QtCore.QRect(10, 100, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.sss_txt = QtGui.QLineEdit(self.generalInfo_frame)
        self.sss_txt.setGeometry(QtCore.QRect(270, 40, 241, 33))
        self.sss_txt.setObjectName(_fromUtf8("sss_txt"))
        self.philhealth_txt = QtGui.QLineEdit(self.generalInfo_frame)
        self.philhealth_txt.setGeometry(QtCore.QRect(270, 100, 241, 33))
        self.philhealth_txt.setObjectName(_fromUtf8("philhealth_txt"))
        self.pagibig_txt = QtGui.QLineEdit(self.generalInfo_frame)
        self.pagibig_txt.setGeometry(QtCore.QRect(270, 160, 241, 33))
        self.pagibig_txt.setObjectName(_fromUtf8("pagibig_txt"))
        self.tin_txt = QtGui.QLineEdit(self.generalInfo_frame)
        self.tin_txt.setGeometry(QtCore.QRect(270, 220, 241, 33))
        self.tin_txt.setObjectName(_fromUtf8("tin_txt"))
        self.label_20 = QtGui.QLabel(self.generalInfo_frame)
        self.label_20.setGeometry(QtCore.QRect(270, 20, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.generalInfo_frame)
        self.label_21.setGeometry(QtCore.QRect(270, 80, 191, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.generalInfo_frame)
        self.label_22.setGeometry(QtCore.QRect(270, 140, 151, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.generalInfo_frame)
        self.label_23.setGeometry(QtCore.QRect(270, 200, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.checkBox_mon = QtGui.QCheckBox(self.generalInfo_frame)
        self.checkBox_mon.setGeometry(QtCore.QRect(100, 100, 90, 23))
        self.checkBox_mon.setObjectName(_fromUtf8("checkBox_mon"))
        self.checkBox_tue = QtGui.QCheckBox(self.generalInfo_frame)
        self.checkBox_tue.setGeometry(QtCore.QRect(100, 130, 90, 23))
        self.checkBox_tue.setObjectName(_fromUtf8("checkBox_tue"))
        self.checkBox_wed = QtGui.QCheckBox(self.generalInfo_frame)
        self.checkBox_wed.setGeometry(QtCore.QRect(100, 160, 111, 23))
        self.checkBox_wed.setObjectName(_fromUtf8("checkBox_wed"))
        self.checkBox_thu = QtGui.QCheckBox(self.generalInfo_frame)
        self.checkBox_thu.setGeometry(QtCore.QRect(100, 190, 90, 23))
        self.checkBox_thu.setObjectName(_fromUtf8("checkBox_thu"))
        self.checkBox_fri = QtGui.QCheckBox(self.generalInfo_frame)
        self.checkBox_fri.setGeometry(QtCore.QRect(100, 220, 90, 23))
        self.checkBox_fri.setObjectName(_fromUtf8("checkBox_fri"))
        self.checkBox_sat = QtGui.QCheckBox(self.generalInfo_frame)
        self.checkBox_sat.setGeometry(QtCore.QRect(100, 250, 90, 23))
        self.checkBox_sat.setObjectName(_fromUtf8("checkBox_sat"))
        self.cancel_btn = QtGui.QPushButton(self.centralwidget)
        self.cancel_btn.setGeometry(QtCore.QRect(660, 650, 111, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cancel_btn.setFont(font)
        self.cancel_btn.setFocusPolicy(QtCore.Qt.TabFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancel_btn.setIcon(icon1)
        self.cancel_btn.setIconSize(QtCore.QSize(30, 30))
        self.cancel_btn.setObjectName(_fromUtf8("cancel_btn"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(540, 410, 231, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(550, 430, 211, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.train_btn = QtGui.QToolButton(self.centralwidget)
        self.train_btn.setGeometry(QtCore.QRect(580, 470, 161, 151))
        self.train_btn.setStyleSheet(_fromUtf8("QToolButton{border: None;}"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icons/facerecoglogo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.train_btn.setIcon(icon2)
        self.train_btn.setIconSize(QtCore.QSize(200, 200))
        self.train_btn.setObjectName(_fromUtf8("train_btn"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 241, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 370, 231, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_24 = QtGui.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(540, 370, 231, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet(_fromUtf8("color: orangered;"))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        RegisterWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(RegisterWindow)
        QtCore.QMetaObject.connectSlotsByName(RegisterWindow)
        RegisterWindow.setTabOrder(self.username_txt, self.password_txt)
        RegisterWindow.setTabOrder(self.password_txt, self.confirm_txt)
        RegisterWindow.setTabOrder(self.confirm_txt, self.fname_txt)
        RegisterWindow.setTabOrder(self.fname_txt, self.mname_txt)
        RegisterWindow.setTabOrder(self.mname_txt, self.lname_txt)
        RegisterWindow.setTabOrder(self.lname_txt, self.gmail_txt)
        RegisterWindow.setTabOrder(self.gmail_txt, self.address_txt)
        RegisterWindow.setTabOrder(self.address_txt, self.birthday_txt)
        RegisterWindow.setTabOrder(self.birthday_txt, self.male_radio)
        RegisterWindow.setTabOrder(self.male_radio, self.female_radio)
        RegisterWindow.setTabOrder(self.female_radio, self.height_txt)
        RegisterWindow.setTabOrder(self.height_txt, self.contact_txt)
        RegisterWindow.setTabOrder(self.contact_txt, self.position_combo)
        RegisterWindow.setTabOrder(self.position_combo, self.rate_combo)
        RegisterWindow.setTabOrder(self.rate_combo, self.checkBox_mon)
        RegisterWindow.setTabOrder(self.checkBox_mon, self.checkBox_tue)
        RegisterWindow.setTabOrder(self.checkBox_tue, self.checkBox_wed)
        RegisterWindow.setTabOrder(self.checkBox_wed, self.checkBox_thu)
        RegisterWindow.setTabOrder(self.checkBox_thu, self.checkBox_fri)
        RegisterWindow.setTabOrder(self.checkBox_fri, self.checkBox_sat)
        RegisterWindow.setTabOrder(self.checkBox_sat, self.sss_txt)
        RegisterWindow.setTabOrder(self.sss_txt, self.philhealth_txt)
        RegisterWindow.setTabOrder(self.philhealth_txt, self.pagibig_txt)
        RegisterWindow.setTabOrder(self.pagibig_txt, self.tin_txt)
        RegisterWindow.setTabOrder(self.tin_txt, self.train_btn)
        RegisterWindow.setTabOrder(self.train_btn, self.cancel_btn)

    def retranslateUi(self, RegisterWindow):
        RegisterWindow.setWindowTitle(_translate("RegisterWindow", "Employee Registration", None))
        self.username_txt.setPlaceholderText(_translate("RegisterWindow", "Username", None))
        self.password_txt.setPlaceholderText(_translate("RegisterWindow", "Password", None))
        self.gmail_txt.setPlaceholderText(_translate("RegisterWindow", ".gmail.com", None))
        self.confirm_txt.setPlaceholderText(_translate("RegisterWindow", "Confirm Password", None))
        self.lname_txt.setPlaceholderText(_translate("RegisterWindow", "Last Name", None))
        self.mname_txt.setPlaceholderText(_translate("RegisterWindow", "Middle Name", None))
        self.fname_txt.setPlaceholderText(_translate("RegisterWindow", "First Name", None))
        self.address_txt.setPlaceholderText(_translate("RegisterWindow", "Address", None))
        self.birthday_txt.setDisplayFormat(_translate("RegisterWindow", "yyyy-MM-dd", None))
        self.label_3.setText(_translate("RegisterWindow", "Birthday:", None))
        self.male_radio.setText(_translate("RegisterWindow", "Male", None))
        self.female_radio.setText(_translate("RegisterWindow", "Female", None))
        self.label_4.setText(_translate("RegisterWindow", "Gender:", None))
        self.height_txt.setPlaceholderText(_translate("RegisterWindow", "Height", None))
        self.contact_txt.setPlaceholderText(_translate("RegisterWindow", "Contact Number", None))
        self.label_10.setText(_translate("RegisterWindow", "Username:", None))
        self.label_11.setText(_translate("RegisterWindow", "Password:", None))
        self.label_12.setText(_translate("RegisterWindow", "Confirm Password:", None))
        self.label_13.setText(_translate("RegisterWindow", "First Name:", None))
        self.label_14.setText(_translate("RegisterWindow", "Middle Name:", None))
        self.label_15.setText(_translate("RegisterWindow", "Last Name:", None))
        self.label_16.setText(_translate("RegisterWindow", "Gmail:", None))
        self.label_17.setText(_translate("RegisterWindow", "Address:", None))
        self.label_18.setText(_translate("RegisterWindow", "Height:", None))
        self.label_19.setText(_translate("RegisterWindow", "Contact No:", None))
        self.label_5.setText(_translate("RegisterWindow", "Position:", None))
        self.label_6.setText(_translate("RegisterWindow", "Rate:", None))
        self.label_7.setText(_translate("RegisterWindow", "Day-Off:", None))
        self.sss_txt.setPlaceholderText(_translate("RegisterWindow", "SSS Number", None))
        self.philhealth_txt.setPlaceholderText(_translate("RegisterWindow", "Philhealth Number", None))
        self.pagibig_txt.setPlaceholderText(_translate("RegisterWindow", "PAGIBIG Number", None))
        self.tin_txt.setPlaceholderText(_translate("RegisterWindow", "TIN Number", None))
        self.label_20.setText(_translate("RegisterWindow", "SSS Number:", None))
        self.label_21.setText(_translate("RegisterWindow", "PHILHEALTH Number:", None))
        self.label_22.setText(_translate("RegisterWindow", "PAGIBIG NUMBER:", None))
        self.label_23.setText(_translate("RegisterWindow", "TIN:", None))
        self.checkBox_mon.setText(_translate("RegisterWindow", "Monday", None))
        self.checkBox_tue.setText(_translate("RegisterWindow", "Tuesday", None))
        self.checkBox_wed.setText(_translate("RegisterWindow", "Wednesday", None))
        self.checkBox_thu.setText(_translate("RegisterWindow", "Thursday", None))
        self.checkBox_fri.setText(_translate("RegisterWindow", "Friday", None))
        self.checkBox_sat.setText(_translate("RegisterWindow", "Saturday", None))
        self.cancel_btn.setText(_translate("RegisterWindow", "Cancel", None))
        self.label_8.setText(_translate("RegisterWindow", "Proceed to data set capturing", None))
        self.label_9.setText(_translate("RegisterWindow", "to complete the registration", None))
        self.train_btn.setText(_translate("RegisterWindow", "...", None))
        self.label.setText(_translate("RegisterWindow", "Profile Information", None))
        self.label_2.setText(_translate("RegisterWindow", "Job Configurations", None))
        self.label_24.setText(_translate("RegisterWindow", "Complete the Registration", None))

