# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIs/SalaryWindow.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SalaryWindow(object):
    def setupUi(self, SalaryWindow):
        SalaryWindow.setObjectName(_fromUtf8("SalaryWindow"))
        SalaryWindow.resize(1111, 590)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/favicon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SalaryWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(SalaryWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 190, 311, 381))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 307, 377))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 100, 181, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.btn_search = QtGui.QPushButton(self.centralwidget)
        self.btn_search.setGeometry(QtCore.QRect(230, 150, 31, 31))
        self.btn_search.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_search.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/search (1).png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_search.setIcon(icon1)
        self.btn_search.setIconSize(QtCore.QSize(30, 30))
        self.btn_search.setObjectName(_fromUtf8("btn_search"))
        self.search_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.search_lineEdit.setGeometry(QtCore.QRect(10, 150, 221, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.search_lineEdit.setFont(font)
        self.search_lineEdit.setText(_fromUtf8(""))
        self.search_lineEdit.setObjectName(_fromUtf8("search_lineEdit"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1020, 10, 81, 71))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8("icons/payroll.png")))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(360, 90, 741, 481))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(20, 20, 301, 191))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.lbl_days_present = QtGui.QLabel(self.frame_2)
        self.lbl_days_present.setGeometry(QtCore.QRect(20, 110, 271, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_days_present.setFont(font)
        self.lbl_days_present.setObjectName(_fromUtf8("lbl_days_present"))
        self.lbl_days_absent = QtGui.QLabel(self.frame_2)
        self.lbl_days_absent.setGeometry(QtCore.QRect(20, 150, 261, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_days_absent.setFont(font)
        self.lbl_days_absent.setObjectName(_fromUtf8("lbl_days_absent"))
        self.lbl_total_time = QtGui.QLabel(self.frame_2)
        self.lbl_total_time.setGeometry(QtCore.QRect(20, 70, 241, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_total_time.setFont(font)
        self.lbl_total_time.setObjectName(_fromUtf8("lbl_total_time"))
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 181, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.frame_3 = QtGui.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(20, 220, 411, 231))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.lbl_pagibig = QtGui.QLabel(self.frame_3)
        self.lbl_pagibig.setGeometry(QtCore.QRect(20, 130, 381, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_pagibig.setFont(font)
        self.lbl_pagibig.setObjectName(_fromUtf8("lbl_pagibig"))
        self.lbl_philhealth = QtGui.QLabel(self.frame_3)
        self.lbl_philhealth.setGeometry(QtCore.QRect(20, 100, 381, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_philhealth.setFont(font)
        self.lbl_philhealth.setObjectName(_fromUtf8("lbl_philhealth"))
        self.lbl_sss = QtGui.QLabel(self.frame_3)
        self.lbl_sss.setGeometry(QtCore.QRect(20, 70, 381, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_sss.setFont(font)
        self.lbl_sss.setObjectName(_fromUtf8("lbl_sss"))
        self.label_5 = QtGui.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 181, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lbl_tax = QtGui.QLabel(self.frame_3)
        self.lbl_tax.setGeometry(QtCore.QRect(20, 160, 331, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_tax.setFont(font)
        self.lbl_tax.setObjectName(_fromUtf8("lbl_tax"))
        self.lbl_total_deductions = QtGui.QLabel(self.frame_3)
        self.lbl_total_deductions.setGeometry(QtCore.QRect(20, 190, 351, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_total_deductions.setFont(font)
        self.lbl_total_deductions.setObjectName(_fromUtf8("lbl_total_deductions"))
        self.lbl_special_pay = QtGui.QLabel(self.frame)
        self.lbl_special_pay.setGeometry(QtCore.QRect(370, 30, 361, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_special_pay.setFont(font)
        self.lbl_special_pay.setObjectName(_fromUtf8("lbl_special_pay"))
        self.lbl_gross_pay = QtGui.QLabel(self.frame)
        self.lbl_gross_pay.setGeometry(QtCore.QRect(370, 70, 361, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_gross_pay.setFont(font)
        self.lbl_gross_pay.setObjectName(_fromUtf8("lbl_gross_pay"))
        self.lbl_period = QtGui.QLabel(self.frame)
        self.lbl_period.setGeometry(QtCore.QRect(370, 110, 361, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_period.setFont(font)
        self.lbl_period.setObjectName(_fromUtf8("lbl_period"))
        self.lbl_status = QtGui.QLabel(self.frame)
        self.lbl_status.setGeometry(QtCore.QRect(370, 150, 361, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_status.setFont(font)
        self.lbl_status.setObjectName(_fromUtf8("lbl_status"))
        self.netpay_frame = QtGui.QFrame(self.frame)
        self.netpay_frame.setGeometry(QtCore.QRect(450, 370, 271, 81))
        self.netpay_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.netpay_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.netpay_frame.setObjectName(_fromUtf8("netpay_frame"))
        self.lbl_net_pay = QtGui.QLabel(self.netpay_frame)
        self.lbl_net_pay.setGeometry(QtCore.QRect(10, 30, 251, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_net_pay.setFont(font)
        self.lbl_net_pay.setObjectName(_fromUtf8("lbl_net_pay"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(360, 40, 181, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lbl_name = QtGui.QLabel(self.centralwidget)
        self.lbl_name.setGeometry(QtCore.QRect(10, 10, 421, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_name.setFont(font)
        self.lbl_name.setObjectName(_fromUtf8("lbl_name"))
        self.lbl_id = QtGui.QLabel(self.centralwidget)
        self.lbl_id.setGeometry(QtCore.QRect(10, 30, 251, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_id.setFont(font)
        self.lbl_id.setObjectName(_fromUtf8("lbl_id"))
        self.lbl_position = QtGui.QLabel(self.centralwidget)
        self.lbl_position.setGeometry(QtCore.QRect(10, 50, 251, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_position.setFont(font)
        self.lbl_position.setObjectName(_fromUtf8("lbl_position"))
        SalaryWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SalaryWindow)
        QtCore.QMetaObject.connectSlotsByName(SalaryWindow)

    def retranslateUi(self, SalaryWindow):
        SalaryWindow.setWindowTitle(_translate("SalaryWindow", "Salary Logs", None))
        self.label.setText(_translate("SalaryWindow", "Salary History", None))
        self.lbl_days_present.setText(_translate("SalaryWindow", "No. of Days Present: ", None))
        self.lbl_days_absent.setText(_translate("SalaryWindow", "No. of Days Absent: ", None))
        self.lbl_total_time.setText(_translate("SalaryWindow", "Total Time: ", None))
        self.label_4.setText(_translate("SalaryWindow", "Time Report", None))
        self.lbl_pagibig.setText(_translate("SalaryWindow", "PAG-IBIG contribution: PHP ", None))
        self.lbl_philhealth.setText(_translate("SalaryWindow", "PHILHEALTH Contribution: PHP ", None))
        self.lbl_sss.setText(_translate("SalaryWindow", "SSS Contirbution: PHP ", None))
        self.label_5.setText(_translate("SalaryWindow", "Deductions", None))
        self.lbl_tax.setText(_translate("SalaryWindow", "Tax: PHP ", None))
        self.lbl_total_deductions.setText(_translate("SalaryWindow", "Total: PHP ", None))
        self.lbl_special_pay.setText(_translate("SalaryWindow", "Special Pay: PHP ", None))
        self.lbl_gross_pay.setText(_translate("SalaryWindow", "Gross Pay: PHP ", None))
        self.lbl_period.setText(_translate("SalaryWindow", "Period: ", None))
        self.lbl_status.setText(_translate("SalaryWindow", "Status: ", None))
        self.lbl_net_pay.setText(_translate("SalaryWindow", "Net Pay: PHP ", None))
        self.label_3.setText(_translate("SalaryWindow", "Salary Report", None))
        self.lbl_name.setText(_translate("SalaryWindow", "Name: ", None))
        self.lbl_id.setText(_translate("SalaryWindow", "ID: ", None))
        self.lbl_position.setText(_translate("SalaryWindow", "Position: ", None))

